asynq/tests/test_debug.py
`test_extract_traceback` was failing on python3 because six.reraise
attaches itself in the traceback only in python3.
=> test: make tests pass for python3

asynq/debug.py
I encountered this when I had run import ipdb, which apparently creates the __IPYTHON__ pseudo-builtin as a side effect.
=> debug: handle case where __IPYTHON__ is set but we're not in a shell

asynq/tests/test_tools.py, asynq/tools.py
This fixes a regression introduced by #17. The new test uses `acached_per_instance` on a non-hashable class.
I also added a test that explicitly checks that an instance's cache is cleared up after the instance is GCed.
=> acached_per_instance: fix for non-hashable instances

asynq/async_task.pxd, asynq/async_task.py, asynq/debug.py
because `inspect.getframeinfo` is potentially very slow
=> Defer calling inspect.getframeinfo until traceback line generation

asynq/_debug.pxd, asynq/_debug.py, asynq/async_task.py, asynq/debug.py, asynq/scheduler.py
for https://github.com/quora/asynq/issues/28
=> debug: add an option to log synchronous calls

asynq/debug.py
traceback.format_tb already returns unicode in Python 2, so we should also
return unicode here.
=> asynq.debug: fix if exception trace contains non-ASCII characters

asynq/debug.py, asynq/tests/test_debug.py
In Python 3, exceptions raised while handling another exception are
preserved, but asynq.debug.format_error still only prints the last
part of the stack trace.
=> debug: properly print chained stack traces

asynq/__init__.py, asynq/_debug.pxd, asynq/_debug.py, asynq/async_task.pxd, asynq/async_task.py, asynq/debug.py, asynq/profiler.pxd, asynq/profiler.py, asynq/scheduler.py, asynq/tests/test_profiler.py, setup.py
Python's standard profiling functions are not working well with AsyncTask as Asynq scheduler controls the tasks and therefore their stack traces are different from original function calls. 
To provide a way to find hotspots in async tasks, we added this performance profiling mode.
=> Support profiling for asynq tasks.

asynq/decorators.py
Without this change, using async_call on functions that define
.async but not .asynq would throw an AttributeError.
=> async_call: support functions with .async

asynq/scheduler.pxd
this should allow memoryerrors to surface to the caller.
=> asynq/continue_with_task: let exceptions be propogated

.travis.yml, asynq/futures.pxd, asynq/futures.py, asynq/tests/test_futures.py, requirements.txt
In the most recent Cython version, the pickling behavior changed. This
PR adds tests for pickling and makes sure they work with the most
recent version of Cython.
=> fix pickling of ConstFuture

asynq/scheduler.py, asynq/tests/test_active_task.py
Save old active task locally in case the global variable changes during execution of the task
=> Scheduler bug fix

asynq/tests/test_tools.py, asynq/tools.py
Calling task.value() in an on_computed callback was resulting in an exception being thrown to the asynq scheduler, causing unexpected behavior.
=> acached per instance: simplify implementation

asynq/tools.py
We were missing a `return` statement.
=> fix Python 2 syntax

setup.py
It's needed for Cython to compile asynq's pxds.
=> add qcore to setup_requires

asynq/mock_.py
If both exist, prefer the one in the stdlib even if "mock" also exists.
=> if mock and unittest.mock exist, prefer stdlib

asynq/tests/test_active_task.py, asynq/tests/test_tools.py, asynq/tools.py, setup.py
While testing Python 3.7, I discovered that `deduplicate()` as currently written works only with `.asynq()`, not `.async()`.
This PR also fixes some usage of `.async` in tests to prepare for supporting 3.7. Before we can actually support 3.7, we need to fix some Cython issues though.
=> fix deduplicate.async

.travis.yml, requirements.txt, setup.py, travis/build-wheels.sh
Per https://github.com/quora/asynq/issues/66, it'd be useful to provide pre-built wheels to users of this library.
I mostly copied from `python-manylinux-demo`: https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh. This change makes it so that travis pulls the manylinux Docker image, builds and tests inside there, and then the built artifacts are available in a directory that is created in the current working directory (`/io/wheelhouse` in the Docker image, just `wheelhouse` from the perspective of Travis).
A notable change I did make was removing python 3.3 from the Travis build matrix because the manylinux Docker image does not support it. Is Python 3.3 support worth special casing it in the Travis environment?
Unlike Circle CI, which makes test artifacts …
=> Build wheels in Travis

asynq/async_task.pxd, asynq/async_task.py, asynq/batching.pxd, asynq/batching.py, asynq/scheduler.py, asynq/tests/test_profiler.py
Previously, we only support AsyncTask information - this change makes Batch and BatchItems also report information to the profiler so that we can use it to get a more complete picture of the async call tree.
=> profiler: Support Batch and BatchItem(s)

.travis.yml, asynq/batching.py, asynq/tools.py, requirements.txt, setup.py
It turned out that a recent change accidentally removed tests from our Travis setup. Oops.
This commit fixes the Travis configuration and the tests that had been broken since.
I also required Cython <0.29 because installation fails with an error about pythran on more recent Cython versions; I haven't yet had time to look into it.
=> fix tests and Travis setup

asynq/contexts.py
Otherwise we risk leaving a stray reference around to the task, which could lead to memory leaks.
=> delete _active_task attribute on AsyncContexts

asynq/async_task.pxd, asynq/async_task.py
This commit adds a flag that captures whether a task is running or not. It mirrors asynq3 in this aspect.
=> Add ability to access whether a task is running or not

README.rst, asynq/batching.py
The only change of substance here is in the `_flush` docstring, which was confusing bc it referred to a requirement that no longer exists now that `_try_switch_active_batch` is called in `_compute`
=> README/comments: update to match code state

requirements.txt, setup.py, tox.ini
Older versions of Cython don't work with Python 3.9.
=> drop Cython maximum version

asynq/tools.pyi
to demonstrate why this is a problem you can run `mypy` on a file with the following:
```
from asynq.tools import AsyncTimer
with AsyncTimer() as t:
pass
print(t.total_time)
```
=> tools: fix stub for AsyncTimer

asynq/async_task.py, asynq/tests/test_active_task.py, asynq/tests/test_tools.py, asynq/tools.py
There are small typos in:
- asynq/async_task.py
- asynq/tests/test_active_task.py
- asynq/tests/test_tools.py
- asynq/tools.py
Fixes:
- Should read `synchronous` rather than `synchonous`.
- Should read `separate` rather than `seperate`.
- Should read `current` rather than `curent`.
- Should read `accommodate` rather than `accomodate`.
Closes #105
=> docs: fix a few simple typos

asynq/contexts.pyi
They do not exist when the module is Cythonized, because they're cdef functions.
=> remove enter_context and leave_context from stub

setup.py
Cython==3.0.0 has backwards incompatible changes that break setup
=> pin Cython for setup

asynq/tools.pyi
I copied the typing from qcore.retry
=> typing: fix aretry typing to match docstring

asynq/decorators.py, asynq/tests/test_asynq_to_async.py
This enables the use of @asynq.asynq(asyncio_fn=..) in class methods.
=> Add AsyncDecoratorBinder.asyncio()

asynq/decorators.py, asynq/tests/test_asynq_to_async.py
.asyncio() logic in `PureAsyncDecorator._call_pure` was shadowed by `AsyncProxyDecorator._call_pure`.
=> Fix async_proxy + .asyncio()

asynq/decorators.py, asynq/tests/test_decorators.py
There was a bug where `async_call.asyncio()` returned `futures.ConstFuture`.
=> Fix async_call.asyncio() and ConstFuture

asynq/asynq_to_async.py, asynq/decorators.py, asynq/tests/test_asynq_to_async.py
This PR addressed two behaviors:
- Propagates raised errors to the caller so that the caller can catch the exception.
- If an asynq function yields a sequence of tasks, cancels all other tasks if any of them fail.
=> Make the behavior consistent for asyncio and asynq: raised error.

asynq/asynq_to_async.py, asynq/tests/test_asynq_to_async.py
Previously, I replaced `asyncio.gather` with `asyncio.wait`. However `asyncio.wait` throws an error when provided with an  empty list of tasks whereas `asyncio.gather` doesn't. 
Fix that case and added a test case.
=> asynq_to_async: handle edge case - empty list of tasks

asynq/decorators.py, asynq/tests/test_decorators.py
AsyncAndSyncPairDecorator wasn't forwarding asyncio_fn to the superclass. 
That caused an issue where asyncio_fn was unavailable when the sync_fn paremeter was provided together.
=> Fix AsyncAndSyncPairDecorator.__init__()

asynq/contexts.py, asynq/decorators.py, asynq/tests/test_asynq_to_async.py, requirements.txt
Fix the error '_asyncio.Task' object has no attribute '_asynq_contexts' when a task is cancelled.
=> Fix leave_context_asyncio to handle cancelled asyncio task

asynq/decorators.pyi
```py
import asyncio
from asynq import asynq
@asynq()
def f(arg1: int, arg2: str):
pass
async def main():
await f.asyncio(1, "2")
await f.asyncio(1, arg2="2")
await f.asyncio(arg1=1, arg2="2")
await f.asyncio(arg1="1", arg2=2)
asyncio.run(main())
```
`pyright test.py` reports
```sh
asynq/test.py
asynq/test.py:15:26 - error: Argument of type "Literal['1']" cannot be assigned to parameter "arg1" of type "int" in function "asyncio"
  "Literal['1']" is incompatible with "int" (reportArgumentType)
asynq/test.py:15:36 - error: Argument of type "Literal[2]" cannot be assigned to parameter "arg2" of type "str" in function "asyncio"
  "Literal[2]" is incompatible with "str" (reportArgumentType)
2 errors, 0 warnings, 0 informations
```
=> Use ParamSpec in .asyncio()

.github/workflows/publish.yml
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
macos-11 is deprecated and macos-12 reaches EOL in 2 months
=> Update CI OS

asynq/mock_.py, asynq/tests/test_mock.py
We introduced asynq_to_async module but didn't add tests for mocks.
When using asynq with `.asyncio` in conjunction with asynq.mock_.patch on an @asynq() decorated function, the `.asyncio` accessor leads to a a MagicMock and can't be awaited
This fixes that and adds unit tests
=> asynq: fix asyncio mock
